/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ProxyRequestPayload {
  path: string
  body: string
  authorization?: string
}
export declare function proxyRequestBlocking(payload: ProxyRequestPayload): Promise<string>
export declare function proxyRequestStreaming(payload: ProxyRequestPayload, onChunk: (chunk: string) => void, onEnd: () => void, onError: (error: string) => void): Promise<void>
export interface StartSidecarPayload {
  path: string
}
export declare function startSidecar(payload: StartSidecarPayload, onOutput: (output: string) => void): void
export declare function stopSidecar(): void
